spring:
  output:
    ansi:
      enabled: always
  jooq:
    sql-dialect: POSTGRES
    bind-offset-date-time-type: false
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data-pg.sql
  data:
    r2dbc:
      repositories:
        enabled: false
  r2dbc:
    url: '@db.url@'
    username: '@db.user@'
    password: '@db.password@'
  flyway:
    enabled: false
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

camel:
  springboot:
    name: geocoder
  route:
    producer:
      enqueue-request-solver: direct://enqueue-request-solver
      enqueue-solution-request: direct://enqueue-solution-request
      broadcast-solution: direct://broadcast-solution
      broadcast-cancel-solver: direct://broadcast-cancel-solver

      request-solver: hazelcast-queue://request-solver-queue?hazelcastInstanceName=opta_router
      solution-request: hazelcast-queue://solution-request-queue?hazelcastInstanceName=opta_router
      solution-topic: hazelcast-topic://solution-topic?hazelcastInstanceName=opta_router
      cancel-solver-topic: hazelcast-topic://cancel-solver-topic?hazelcastInstanceName=opta_router&reliable=true
    consumer:
      enqueue-request-solver: direct://enqueue-request-solver
      enqueue-solution-request: direct://enqueue-solution-request
      broadcast-solution: direct://broadcast-solution
      broadcast-cancel-solver: direct://broadcast-cancel-solver

      request-solver: hazelcast-queue://request-solver-queue?hazelcastInstanceName=opta_router&queueConsumerMode=poll
      solution-request: hazelcast-queue://solution-request-queue?hazelcastInstanceName=opta_router&queueConsumerMode=poll
      solution-topic: hazelcast-topic://solution-topic?hazelcastInstanceName=opta_router
      cancel-solver-topic: hazelcast-topic://cancel-solver-topic?hazelcastInstanceName=opta_router&reliable=true

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,env,loggers,mappings,scheduledtasks,threaddump,heapdump,beans,sessions

springdoc:
  api-docs:
    enabled: true

solver:
  termination:
    time-limit: 5m
