
spring:
  output:
    ansi:
      enabled: always
  jooq:
    sql-dialect: POSTGRES
    bind-offset-date-time-type: false
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data-pg.sql
  data:
    r2dbc:
      repositories:
        enabled: false
  r2dbc:
    url: '@db.url@'
    username: '@db.user@'
    password: '@db.password@'
  flyway:
    enabled: false
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  hazelcast:
    config: classpath:hazelcast.yaml
  jmx:
    enabled: true
  docker:
    compose:
      enabled: false

camel:
  springboot:
    name: geocoder
    backlog-tracing: true
    use-mdc-logging: true
    tracing: true
    dev-console-enabled: true
  route:
    producer:
      enqueue-request-solver: direct://enqueue-request-solver
      enqueue-solution-request: direct://enqueue-solution-request
      broadcast-solution: direct://broadcast-solution
      broadcast-cancel-solver: direct://broadcast-cancel-solver

      request-solver: hazelcast-queue://request-solver-queue?hazelcastInstanceName=geocoder
      solution-request: hazelcast-queue://solution-request-queue?hazelcastInstanceName=geocoder
      solution-topic: hazelcast-topic://solution-topic?hazelcastInstanceName=geocoder
      cancel-solver-topic: hazelcast-topic://cancel-solver-topic?hazelcastInstanceName=geocoder&reliable=true
    consumer:
      enqueue-request-solver: direct://enqueue-request-solver
      enqueue-solution-request: direct://enqueue-solution-request
      broadcast-solution: direct://broadcast-solution
      broadcast-cancel-solver: direct://broadcast-cancel-solver

      request-solver: hazelcast-queue://request-solver-queue?hazelcastInstanceName=geocoder&queueConsumerMode=listen
      solution-request: hazelcast-queue://solution-request-queue?hazelcastInstanceName=geocoder&queueConsumerMode=listen
      solution-topic: hazelcast-topic://solution-topic?hazelcastInstanceName=geocoder
      cancel-solver-topic: hazelcast-topic://cancel-solver-topic?hazelcastInstanceName=geocoder&reliable=true
  debug:
    enabled: true
  component:
    hazelcast-queue:
      enabled: true
      hazelcast-instance: geocoder
    hazelcast-topic:
      enabled: true
      hazelcast-instance: geocoder
  main:
    dev-console-enabled: true

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

hawtio:
  disableProxy: true
  authenticationEnabled: false

springdoc:
  api-docs:
    enabled: true

solver:
  termination:
    time-limit: 5m

logging.level.org.jooq.Constants: off
logging.level.com.hazelcast.system.logo: off
